### ISSUE TITLE
Tunnel SSH Connection over 2222 port ... not running!!

### ISSUE THREAD

**Issue by acarravedo** [TeamSQL/desktop-app#117]
OS: Darwin x64 16.5.0
VERSION: 0.9.95
---------------
Database Type: MySQL
How can this issue be reproduced? YES!!

When configure connection using SSH Tunnel ... work test but not connection on exit and connection after.

![image](https://cloud.githubusercontent.com/assets/1014060/26405200/e47af06a-4094-11e7-98cf-c668ac66e149.png)
![image](https://cloud.githubusercontent.com/assets/1014060/26405213/ef5c5ece-4094-11e7-8b1e-65313bc6a155.png)
![image](https://cloud.githubusercontent.com/assets/1014060/26405224/f6af974a-4094-11e7-8b63-b2f74401b3f7.png)

**Comment by fordracerguy** [comment]
Same thing happens to me in Linux.

**Comment by erenbaydemir** [comment]
Thank you for reporting this. We confirmed the issue and fixed it. The fix will be available in 0.9.98 release which is due this week.

**Comment by gabiudrescu** [comment]
I started to receive the same error today, totally out of nowhere. I am using Linux, the latest version: v3.4.230.

the error I receive is:

```
Connection to the server has failed. Please check your network and VPN connection (if available) and try again.
```

If I try to test the connection, I receive the error below:

```
Connection failed to the server. Please check your connection settings.
(SSH) Channel open failure: Connection refused
```

If I run the client from CLI, there is the log below when this error happens:
```
error:  { Error: (SSH) Channel open failure: Connection refused
    at SSH2Stream.onFailure (/opt/TeamSQL/resources/app.asar/node_modules/ssh2/lib/client.js:1186:13)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (/opt/TeamSQL/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3708:10)
    at SSH2Stream._transform (/opt/TeamSQL/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/opt/TeamSQL/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12) reason: 'CONNECT_FAILED', lang: '' }
SSH tunnel exists for connection 7860344b-0452-4a58-825f-cb99972fca6b
error:  { Error: (SSH) Channel open failure: Connection refused
    at SSH2Stream.onFailure (/opt/TeamSQL/resources/app.asar/node_modules/ssh2/lib/client.js:1186:13)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (/opt/TeamSQL/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3708:10)
    at SSH2Stream._transform (/opt/TeamSQL/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/opt/TeamSQL/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12) reason: 'CONNECT_FAILED', lang: '' }
SSH tunnel exists for connection 7860344b-0452-4a58-825f-cb99972fca6b
error:  { Error: (SSH) Channel open failure: Connection refused
    at SSH2Stream.onFailure (/opt/TeamSQL/resources/app.asar/node_modules/ssh2/lib/client.js:1186:13)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (/opt/TeamSQL/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3708:10)
    at SSH2Stream._transform (/opt/TeamSQL/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/opt/TeamSQL/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12) reason: 'CONNECT_FAILED', lang: '' }
```

**Comment by gabiudrescu** [comment]
The same error happens on 4.0 Beta:

```
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```
